/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-08-30 18:13:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.P3.Vistas.MenuCriticas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import JavaBeans.TodosEspectaculosJavaBean;
import GeneralDTO.EspectaculoPuntualDTO;
import GeneralDTO.EspectaculoPaseMultipleDTO;
import GeneralDTO.EspectaculoTemporadaDTO;
import GeneralDTO.FechaDTO;
import GeneralDTO.PaseDTO;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

public final class TodasCriticasVista_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("GeneralDTO.EspectaculoPaseMultipleDTO");
    _jspx_imports_classes.add("GeneralDTO.FechaDTO");
    _jspx_imports_classes.add("JavaBeans.TodosEspectaculosJavaBean");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("GeneralDTO.EspectaculoPuntualDTO");
    _jspx_imports_classes.add("GeneralDTO.PaseDTO");
    _jspx_imports_classes.add("GeneralDTO.EspectaculoTemporadaDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      JavaBeans.TodosEspectaculosJavaBean allEspsBean = null;
      synchronized (session) {
        allEspsBean = (JavaBeans.TodosEspectaculosJavaBean) _jspx_page_context.getAttribute("allEspsBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (allEspsBean == null){
          allEspsBean = new JavaBeans.TodosEspectaculosJavaBean();
          _jspx_page_context.setAttribute("allEspsBean", allEspsBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Menú de Críticas</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../CabeceraNavegacion.jsp", out, false);
      out.write('\r');
      out.write('\n');
 
request.getSession().getAttribute("allEspsBean");
if(allEspsBean.getAllPunt() == null)
{
	String redirectURL = "../../../GetTodosEspectaculosRealizadosServlet";
	response.sendRedirect(redirectURL);
}
else
{
	if (allEspsBean != null) {
		
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<div class=\"sticky\">\r\n");
      out.write("		<h1>Menú de Críticas</h1>\r\n");
      out.write("		<input type=\"text\" placeholder=\"Título\" id=\"buscador\">\r\n");
      out.write("		</div>\r\n");
      out.write("				");

				
					for (EspectaculoPuntualDTO punt : allEspsBean.getAllPunt()){
				
      out.write("\r\n");
      out.write("				<div class = \"critica\"> \r\n");
      out.write("					<h2> ");
      out.print( punt.getNombre());
      out.write(" </h2>\r\n");
      out.write("					<div class=\"side\">\r\n");
      out.write("					<form method=\"Post\" action=\"../../../P3/Vistas/MenuCriticas/NuevaCritica.jsp\">\r\n");
      out.write("					    <button type=\"submit\" value=\"Añadir Crítica\">Añadir Critica</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(punt.getNombre() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(punt.getId() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("					<form method=\"Post\" action=\"../../../GetTosdasCriticasServlet\">\r\n");
      out.write("					    <button type=\"submit\" value=\"Ver Críticas\">Ver Criticas</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(punt.getNombre() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(punt.getId() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");

				for (EspectaculoPaseMultipleDTO mult : allEspsBean.getAllMult()){
				
      out.write("\r\n");
      out.write("				<div class = \"critica\"> \r\n");
      out.write("					<h2 class = \"titulo\"> ");
      out.print( mult.getNombre());
      out.write(" </h2>\r\n");
      out.write("					<div class=\"side\">\r\n");
      out.write("					<form method=\"Post\" action=\"../../../P3/Vistas/MenuCriticas/NuevaCritica.jsp\">\r\n");
      out.write("		   			    <button type=\"submit\" value=\"Añadir Crítica\">Añadir Critica</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(mult.getId() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(mult.getNombre() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("				\r\n");
      out.write("					<form method=\"Post\" action=\"../../../GetTodasCriticasServlet\">\r\n");
      out.write("		   			    <button type=\"submit\" value=\"Ver Críticas\">Ver Criticas</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(mult.getNombre() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(mult.getId() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");

			
				for (EspectaculoTemporadaDTO temp : allEspsBean.getAllTemp()){
			
      out.write("\r\n");
      out.write("				<div class = \"critica\"> \r\n");
      out.write("					<h2 class = \"titulo\">");
      out.print( temp.getNombre());
      out.write("</h2>\r\n");
      out.write("					<div class=\"side\">\r\n");
      out.write("					<form method=\"Post\" action=\"../../../P3/Vistas/MenuCriticas/NuevaCritica.jsp\">\r\n");
      out.write("		   			    <button type=\"submit\" value=\"Añadir Crítica\">Añadir Critica</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(temp.getNombre() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(temp.getId() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("					<form method=\"Post\" action=\"../../../GetTodasCriticasServlet\">\r\n");
      out.write("		   			    <button type=\"submit\" value=\"Ver Críticas\">Ver Criticas</button>\r\n");
      out.write("					    <input type=\"hidden\" name=\"nombreEsp\" value= \"");
      out.print(temp.getNombre() );
      out.write("\">\r\n");
      out.write("					    <input type=\"hidden\" name=\"idEsp\" value= \"");
      out.print(temp.getId() );
      out.write("\">\r\n");
      out.write("					</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		}
}
session.setAttribute("allEspsBean", null);


      out.write("\r\n");
      out.write("<script src=\"../../JavaScript/FiltroTecla.js\"> </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
