/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-08-30 15:45:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.P3.Vistas.MenuHomeDatos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HomeUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home User</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);\r\n");
      out.write("body{\r\n");
      out.write("	background: #9aafc7;\r\n");
      out.write("   	font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".foto\r\n");
      out.write("{\r\n");
      out.write(" transition: transform .2s; /* Animation */\r\n");
      out.write("}    \r\n");
      out.write(".foto:hover\r\n");
      out.write("{\r\n");
      out.write("transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write(".cont {  \r\n");
      out.write("  display: grid;\r\n");
      out.write("  grid-template-columns: 1fr 1.3fr 0.55fr 1.3fr 0.55fr 1.3fr 1fr;\r\n");
      out.write("  grid-template-rows: 0.2fr 1.5fr;\r\n");
      out.write("  grid-auto-columns: 1fr;\r\n");
      out.write("  gap: 0px 0px;\r\n");
      out.write("  grid-auto-flow: row;\r\n");
      out.write("  grid-template-areas:\r\n");
      out.write("    \". . . . . . .\"\r\n");
      out.write("    \". users . crit . espectaculos .\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".users { grid-area: users; }\r\n");
      out.write("\r\n");
      out.write(".crit { grid-area: crit; }\r\n");
      out.write("\r\n");
      out.write(".espectaculos { grid-area: espectaculos; }\r\n");
      out.write("\r\n");
      out.write("    div.users, div.crit, div.espectaculos {\r\n");
      out.write("   display: grid;\r\n");
      out.write("  margin-left: auto;\r\n");
      out.write("  margin-right: auto;\r\n");
      out.write("  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.container {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write(".container p{\r\n");
      out.write("  font-size: 2em;\r\n");
      out.write("  color: #fdfdfd;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../CabeceraNavegacion.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"cont\">\r\n");
      out.write("	<div class=\"users\">\r\n");
      out.write("	  <a href=/Practica3/P3/Vistas/MenuHomeDatos/HomeDatosUsuario.jsp><img class=\"foto\" src=\"/Practica3/P3/Imagenes/Usuario.png\" alt=\"data usuario\" style=\"width:100%\"></a>\r\n");
      out.write("	  <div class=\"container\">\r\n");
      out.write("	  <p>Datos personales</p>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"crit\">\r\n");
      out.write("	  <a href=/Practica3/P3/Vistas/MenuHomeDatos/ModificarUsuario.jsp><img class=\"foto\" src=\"/Practica3/P3/Imagenes/Modificar.png\" alt=\"modify usuario\" style=\"width:100%\"></a>\r\n");
      out.write("	  <div class=\"container\">\r\n");
      out.write("	  <p>Modificar sus datos Personales</p>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"espectaculos\">\r\n");
      out.write("	  <a href=/Practica3/P3/Vistas/MenuHomeDatos/EliminarUsuario.jsp><img class=\"foto\" src=\"/Practica3/P3/Imagenes/Papelera.png\" alt=\"delete usuario\" style=\"width:100%\"></a>\r\n");
      out.write("	  <div class=\"container\">\r\n");
      out.write("	  <p>Eliminar su cuenta de usuario</p>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
